export type CubeType = '3x3' | '4x4' | '5x5';

export interface MoveStep {
  move: string;
  title: string;
  instruction: string;
  fingerTrick: string;
  affectedLayer: string;
  spokenText: string;
}

export interface Algorithm {
  id: string;
  cubeType: CubeType;
  category: string;
  stageName: string;
  name: string;
  shortName: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  moves: string[];
  explanation: string;
  tactileTip: string;
  mnemonic?: string;
  moveSteps: MoveStep[];
}

export const CUBE_ALGORITHMS: Algorithm[] = [
  // ==========================================
  // 3x3: BEGINNER METHOD & CFOP
  // ==========================================
  {
    id: '3x3-sexy-move',
    cubeType: '3x3',
    category: 'Beginner Foundations',
    stageName: 'Step 1: First Layer Corners',
    name: 'The "Sexy Move" (Corner Insertion)',
    shortName: 'R U R\' U\'',
    difficulty: 'Beginner',
    moves: ['R', 'U', "R'", "U'"],
    explanation: 'The most foundational 4-move trigger in all of cubing. Used to position and orient corner pieces into the first layer, as well as being the fundamental engine inside OLL and PLL.',
    tactileTip: 'Keep your right thumb on the front center cap and snap the U layer with your right index finger tip.',
    mnemonic: 'Right up, top left, right down, top right.',
    moveSteps: [
      {
        move: 'R',
        title: 'Right Face Clockwise',
        instruction: 'Turn the right layer upwards 90° away from you.',
        fingerTrick: 'Use your right wrist with thumb on front.',
        affectedLayer: 'R',
        spokenText: 'Right clockwise.',
      },
      {
        move: 'U',
        title: 'Up Face Clockwise',
        instruction: 'Turn the top layer 90° to the left.',
        fingerTrick: 'Flick the back-right corner with your right index finger.',
        affectedLayer: 'U',
        spokenText: 'Up clockwise.',
      },
      {
        move: "R'",
        title: 'Right Face Counter-Clockwise',
        instruction: 'Pull the right layer back downwards 90° towards you.',
        fingerTrick: 'Pull downwards with right wrist.',
        affectedLayer: 'R',
        spokenText: 'Right prime.',
      },
      {
        move: "U'",
        title: 'Up Face Counter-Clockwise',
        instruction: 'Turn the top layer 90° to the right.',
        fingerTrick: 'Flick the back-left corner with your left index finger.',
        affectedLayer: 'U',
        spokenText: 'Up prime.',
      },
    ],
  },
  {
    id: '3x3-middle-layer-right',
    cubeType: '3x3',
    category: 'Beginner Foundations',
    stageName: 'Step 2: Second Layer Edges',
    name: 'Middle Layer Edge Insert (Righty)',
    shortName: 'U R U\' R\' U\' F\' U F',
    difficulty: 'Beginner',
    moves: ['U', 'R', "U'", "R'", "U'", "F'", 'U', 'F'],
    explanation: 'Moves a top edge piece down into the front-right middle slot without disturbing your completed white base.',
    tactileTip: 'First push the top edge away from the target slot, pair it with its corner, then insert the pair into the front.',
    mnemonic: 'Away, sexy trigger, rotate to front, insert pair.',
    moveSteps: [
      { move: 'U', title: 'Top Left', instruction: 'Move the top edge away from its target slot.', fingerTrick: 'Right index flick.', affectedLayer: 'U', spokenText: 'Up.' },
      { move: 'R', title: 'Right Up', instruction: 'Raise the right corner up to meet the edge.', fingerTrick: 'Right wrist up.', affectedLayer: 'R', spokenText: 'Right.' },
      { move: "U'", title: 'Top Right', instruction: 'Pair the white corner with the edge.', fingerTrick: 'Left index flick.', affectedLayer: 'U', spokenText: 'Up prime.' },
      { move: "R'", title: 'Right Down', instruction: 'Retract the right column back to the base.', fingerTrick: 'Right wrist down.', affectedLayer: 'R', spokenText: 'Right prime.' },
      { move: "U'", title: 'Position Front', instruction: 'Align the paired block for frontal insertion.', fingerTrick: 'Left index flick.', affectedLayer: 'U', spokenText: 'Up prime.' },
      { move: "F'", title: 'Front Face Counter-Clockwise', instruction: 'Open the front face to receive the pair.', fingerTrick: 'Right index push downwards.', affectedLayer: 'F', spokenText: 'Front prime.' },
      { move: 'U', title: 'Slot Insert', instruction: 'Slide the completed pair into place.', fingerTrick: 'Right index flick.', affectedLayer: 'U', spokenText: 'Up.' },
      { move: 'F', title: 'Restore Front', instruction: 'Rotate front back clockwise to secure the white base.', fingerTrick: 'Right thumb push upwards.', affectedLayer: 'F', spokenText: 'Front.' },
    ],
  },
  {
    id: '3x3-yellow-cross-furuf',
    cubeType: '3x3',
    category: 'Beginner Foundations',
    stageName: 'Step 3: Yellow Cross',
    name: 'Yellow Cross (FUR-U-RUF)',
    shortName: 'F R U R\' U\' F\'',
    difficulty: 'Beginner',
    moves: ['F', 'R', 'U', "R'", "U'", "F'"],
    explanation: 'Transforms any top-layer state (Dot -> 9:00 L-shape -> Horizontal Line) into the completed Yellow Cross.',
    tactileTip: 'Think of it as: Open the front face (F), perform one standard Sexy Move (R U R\' U\'), and close the front face (F\').',
    mnemonic: 'F, Sexy Move, F prime.',
    moveSteps: [
      { move: 'F', title: 'Front Clockwise', instruction: 'Rotate front face 90° clockwise.', fingerTrick: 'Right index push down.', affectedLayer: 'F', spokenText: 'Front.' },
      { move: 'R', title: 'Right Up', instruction: 'Lift the right slot.', fingerTrick: 'Right wrist roll.', affectedLayer: 'R', spokenText: 'Right.' },
      { move: 'U', title: 'Top Left', instruction: 'Flick top layer clockwise.', fingerTrick: 'Right index flick.', affectedLayer: 'U', spokenText: 'Up.' },
      { move: "R'", title: 'Right Down', instruction: 'Return the right column.', fingerTrick: 'Right wrist pull.', affectedLayer: 'R', spokenText: 'Right prime.' },
      { move: "U'", title: 'Top Right', instruction: 'Return top layer.', fingerTrick: 'Left index flick.', affectedLayer: 'U', spokenText: 'Up prime.' },
      { move: "F'", title: 'Front Prime', instruction: 'Restore the front face counter-clockwise.', fingerTrick: 'Right thumb lift.', affectedLayer: 'F', spokenText: 'Front prime.' },
    ],
  },
  {
    id: '3x3-sune',
    cubeType: '3x3',
    category: 'CFOP - OLL',
    stageName: 'Step 4: OLL 27',
    name: 'Sune (Yellow Fish / Edges Swap)',
    shortName: 'R U R\' U R U2 R\'',
    difficulty: 'Intermediate',
    moves: ['R', 'U', "R'", 'U', 'R', 'U2', "R'"],
    explanation: 'One of the most famous speedcubing algorithms. Orients 3 yellow corners while cycling top edges. Recognized by the classic "Fish" pattern pointing to bottom-left.',
    tactileTip: 'The U2 move can be executed as a double-flick: right index followed immediately by right middle finger.',
    mnemonic: 'Right up, top left, right down, top left, right up, top double, right down.',
    moveSteps: [
      { move: 'R', title: 'Right Up', instruction: 'Lift right layer.', fingerTrick: 'Right wrist.', affectedLayer: 'R', spokenText: 'Right.' },
      { move: 'U', title: 'Top Left', instruction: 'Flick top clockwise.', fingerTrick: 'Right index flick.', affectedLayer: 'U', spokenText: 'Up.' },
      { move: "R'", title: 'Right Down', instruction: 'Bring right layer down.', fingerTrick: 'Right wrist.', affectedLayer: 'R', spokenText: 'Right prime.' },
      { move: 'U', title: 'Top Left Again', instruction: 'Flick top clockwise one more time.', fingerTrick: 'Right index flick.', affectedLayer: 'U', spokenText: 'Up.' },
      { move: 'R', title: 'Right Up', instruction: 'Raise right layer back up.', fingerTrick: 'Right wrist.', affectedLayer: 'R', spokenText: 'Right.' },
      { move: 'U2', title: 'Top Double Turn', instruction: 'Spin top layer 180° back around.', fingerTrick: 'Right index-middle double flick.', affectedLayer: 'U', spokenText: 'Up two.' },
      { move: "R'", title: 'Right Down', instruction: 'Lock the completed layer back into place.', fingerTrick: 'Right wrist pull.', affectedLayer: 'R', spokenText: 'Right prime.' },
    ],
  },
  {
    id: '3x3-t-perm',
    cubeType: '3x3',
    category: 'CFOP - PLL',
    stageName: 'Step 5: PLL T-Perm',
    name: 'T-Permutation (Adjacent Corner & Edge Swap)',
    shortName: 'R U R\' U\' R\' F R2 U\' R\' U\' R U R\' F\'',
    difficulty: 'Intermediate',
    moves: ['R', 'U', "R'", "U'", "R'", 'F', 'R2', "U'", "R'", "U'", 'R', 'U', "R'", "F'"],
    explanation: 'Swaps the two right corners and two opposite edges, shaping like the letter T. Essential tournament algorithm for PLL.',
    tactileTip: 'Notice the structure: Sexy Move (R U R\' U\') -> Sledgehammer variant -> Inverse Sexy -> Front Restore.',
    mnemonic: 'Sexy move, transition to F R2, double prime push, finish with sexy and F prime.',
    moveSteps: [
      { move: 'R', title: 'Right', instruction: 'Up.', fingerTrick: 'Right wrist.', affectedLayer: 'R', spokenText: 'Right.' },
      { move: 'U', title: 'Up', instruction: 'Flick.', fingerTrick: 'Index.', affectedLayer: 'U', spokenText: 'Up.' },
      { move: "R'", title: 'Right Prime', instruction: 'Down.', fingerTrick: 'Wrist.', affectedLayer: 'R', spokenText: 'Right prime.' },
      { move: "U'", title: 'Up Prime', instruction: 'Return.', fingerTrick: 'Left index.', affectedLayer: 'U', spokenText: 'Up prime.' },
      { move: "R'", title: 'Right Prime', instruction: 'Down again.', fingerTrick: 'Wrist.', affectedLayer: 'R', spokenText: 'Right prime.' },
      { move: 'F', title: 'Front', instruction: 'Turn front face 90° clockwise.', fingerTrick: 'Right index.', affectedLayer: 'F', spokenText: 'Front.' },
      { move: 'R2', title: 'Right Double', instruction: '180° rotation on the right layer.', fingerTrick: 'Double wrist flick.', affectedLayer: 'R', spokenText: 'Right two.' },
      { move: "U'", title: 'Up Prime', instruction: 'Top counter-clockwise.', fingerTrick: 'Left index.', affectedLayer: 'U', spokenText: 'Up prime.' },
      { move: "R'", title: 'Right Prime', instruction: 'Right downwards.', fingerTrick: 'Right wrist.', affectedLayer: 'R', spokenText: 'Right prime.' },
      { move: "U'", title: 'Up Prime', instruction: 'Top counter-clockwise.', fingerTrick: 'Left index.', affectedLayer: 'U', spokenText: 'Up prime.' },
      { move: 'R', title: 'Right', instruction: 'Right upwards.', fingerTrick: 'Right wrist.', affectedLayer: 'R', spokenText: 'Right.' },
      { move: 'U', title: 'Up', instruction: 'Top clockwise.', fingerTrick: 'Right index.', affectedLayer: 'U', spokenText: 'Up.' },
      { move: "R'", title: 'Right Prime', instruction: 'Right down.', fingerTrick: 'Right wrist.', affectedLayer: 'R', spokenText: 'Right prime.' },
      { move: "F'", title: 'Front Prime', instruction: 'Restore front face counter-clockwise.', fingerTrick: 'Right thumb.', affectedLayer: 'F', spokenText: 'Front prime.' },
    ],
  },
  {
    id: '3x3-h-perm',
    cubeType: '3x3',
    category: 'CFOP - PLL',
    stageName: 'Step 5: PLL H-Perm',
    name: 'H-Permutation (Opposite Edge Cross Swap)',
    shortName: 'M2 U M2 U2 M2 U M2',
    difficulty: 'Intermediate',
    moves: ['M2', 'U', 'M2', 'U2', 'M2', 'U', 'M2'],
    explanation: 'Symmetrically swaps Front-Back edges and Left-Right edges using M (middle slice) double turns.',
    tactileTip: 'Execute M2 using ring-then-middle finger flicks from the bottom-back of the cube for lightning speed.',
    mnemonic: 'M2 U, M2 U2, M2 U, M2.',
    moveSteps: [
      { move: 'M2', title: 'Middle Double', instruction: 'Flick the vertical middle slice 180° upward.', fingerTrick: 'Ring-middle double flick on back.', affectedLayer: 'M', spokenText: 'Middle slice two.' },
      { move: 'U', title: 'Up', instruction: 'Top clockwise 90°.', fingerTrick: 'Right index flick.', affectedLayer: 'U', spokenText: 'Up.' },
      { move: 'M2', title: 'Middle Double', instruction: '180° slice rotation.', fingerTrick: 'Ring-middle double flick.', affectedLayer: 'M', spokenText: 'Middle slice two.' },
      { move: 'U2', title: 'Up Double', instruction: '180° top rotation.', fingerTrick: 'Index-middle double flick.', affectedLayer: 'U', spokenText: 'Up two.' },
      { move: 'M2', title: 'Middle Double', instruction: '180° slice rotation.', fingerTrick: 'Ring-middle double flick.', affectedLayer: 'M', spokenText: 'Middle slice two.' },
      { move: 'U', title: 'Up', instruction: 'Top clockwise 90°.', fingerTrick: 'Right index flick.', affectedLayer: 'U', spokenText: 'Up.' },
      { move: 'M2', title: 'Middle Double', instruction: 'Final 180° slice snap to complete the cube.', fingerTrick: 'Ring-middle double flick.', affectedLayer: 'M', spokenText: 'Middle slice two.' },
    ],
  },

  // ==========================================
  // 4x4: RUBIK'S REVENGE (REDUCTION METHOD)
  // ==========================================
  {
    id: '4x4-center-strip',
    cubeType: '4x4',
    category: '4x4 Centers',
    stageName: 'Stage 1: Center Bars (2x2 Blocks)',
    name: 'Center Strip Insertion & Restoration',
    shortName: 'Rw U Rw\'',
    difficulty: 'Beginner',
    moves: ['Rw', 'U', "Rw'"],
    explanation: 'On a 4x4, there are no fixed center pieces! Centers are composed of 4 movable pieces per face. This fundamental move brings a built 1x2 bar into the target face, rotates it away, and restores the bottom center bar.',
    tactileTip: 'Rw turns the two rightmost layers simultaneously as a single block.',
    mnemonic: 'Wide right up, move top, wide right down.',
    moveSteps: [
      { move: 'Rw', title: 'Right Wide Up', instruction: 'Turn the two right layers together 90° clockwise.', fingerTrick: 'Grip both right layers with right fingers and roll upwards.', affectedLayer: 'Rw', spokenText: 'Right wide.' },
      { move: 'U', title: 'Top Clockwise', instruction: 'Turn the top layer 90° clockwise to rotate the bar out of the slice lane.', fingerTrick: 'Right index finger flick.', affectedLayer: 'U', spokenText: 'Up.' },
      { move: "Rw'", title: 'Right Wide Down', instruction: 'Bring the two right layers back down 90° to preserve opposite centers.', fingerTrick: 'Roll both right layers downwards.', affectedLayer: 'Rw', spokenText: 'Right wide prime.' },
    ],
  },
  {
    id: '4x4-last-two-centers',
    cubeType: '4x4',
    category: '4x4 Centers',
    stageName: 'Stage 1: Last 2 Centers',
    name: 'Last 2 Centers Half-Turn Commutator',
    shortName: 'Rw U Rw\' U Rw U2 Rw\'',
    difficulty: 'Intermediate',
    moves: ['Rw', 'U', "Rw'", 'U', 'Rw', 'U2', "Rw'"],
    explanation: 'When solving the final two 4x4 centers, this algorithm swaps a single 1x2 center bar between the Front and Up faces while protecting all other solved centers.',
    tactileTip: 'This is the wide version of the Sune trigger executed on the outer two right layers.',
    mnemonic: 'Wide Sune trigger.',
    moveSteps: [
      { move: 'Rw', title: 'Wide Up', instruction: 'Lift 2 right layers.', fingerTrick: 'Right wrist.', affectedLayer: 'Rw', spokenText: 'Right wide.' },
      { move: 'U', title: 'Top Left', instruction: 'Flick top face.', fingerTrick: 'Right index.', affectedLayer: 'U', spokenText: 'Up.' },
      { move: "Rw'", title: 'Wide Down', instruction: 'Bring 2 right layers down.', fingerTrick: 'Right wrist.', affectedLayer: 'Rw', spokenText: 'Right wide prime.' },
      { move: 'U', title: 'Top Left', instruction: 'Flick top face again.', fingerTrick: 'Right index.', affectedLayer: 'U', spokenText: 'Up.' },
      { move: 'Rw', title: 'Wide Up', instruction: 'Lift 2 right layers.', fingerTrick: 'Right wrist.', affectedLayer: 'Rw', spokenText: 'Right wide.' },
      { move: 'U2', title: 'Top 180°', instruction: 'Spin top face 180°.', fingerTrick: 'Double flick.', affectedLayer: 'U', spokenText: 'Up two.' },
      { move: "Rw'", title: 'Wide Down', instruction: 'Retract 2 right layers to lock center bar.', fingerTrick: 'Right wrist.', affectedLayer: 'Rw', spokenText: 'Right wide prime.' },
    ],
  },
  {
    id: '4x4-edge-pairing-flip',
    cubeType: '4x4',
    category: '4x4 Edge Pairing',
    stageName: 'Stage 2: Edge Pairing',
    name: 'Edge Flipping Algorithm',
    shortName: 'R U R\' F R\' F\' R',
    difficulty: 'Intermediate',
    moves: ['R', 'U', "R'", 'F', "R'", "F'", 'R'],
    explanation: 'Flips the front-right dedge (double edge) upside down in place. Essential for pairing edges during the freeslice phase and the last two edges (L2E).',
    tactileTip: 'Flows immediately from an R U R\' trigger into a sledgehammer variation F R\' F\' R.',
    mnemonic: 'Lift, flick, drop, face roll, drop, face close, lift.',
    moveSteps: [
      { move: 'R', title: 'Right Up', instruction: 'Lift right layer.', fingerTrick: 'Right wrist.', affectedLayer: 'R', spokenText: 'Right.' },
      { move: 'U', title: 'Up Clockwise', instruction: 'Flick top layer.', fingerTrick: 'Right index.', affectedLayer: 'U', spokenText: 'Up.' },
      { move: "R'", title: 'Right Down', instruction: 'Drop right layer.', fingerTrick: 'Right wrist.', affectedLayer: 'R', spokenText: 'Right prime.' },
      { move: 'F', title: 'Front Clockwise', instruction: 'Turn front face 90°.', fingerTrick: 'Right index push.', affectedLayer: 'F', spokenText: 'Front.' },
      { move: "R'", title: 'Right Down', instruction: 'Drop right layer.', fingerTrick: 'Right wrist.', affectedLayer: 'R', spokenText: 'Right prime.' },
      { move: "F'", title: 'Front Prime', instruction: 'Close front face.', fingerTrick: 'Right thumb.', affectedLayer: 'F', spokenText: 'Front prime.' },
      { move: 'R', title: 'Right Up', instruction: 'Lock flipped edge.', fingerTrick: 'Right wrist.', affectedLayer: 'R', spokenText: 'Right.' },
    ],
  },
  {
    id: '4x4-slice-flip-slice',
    cubeType: '4x4',
    category: '4x4 Edge Pairing',
    stageName: 'Stage 2: Freeslice Edge Pairing',
    name: 'Slice-Flip-Slice (Freeslice Assembly)',
    shortName: 'Uw\' (R U R\' F R\' F\' R) Uw',
    difficulty: 'Intermediate',
    moves: ["Uw'", 'R', 'U', "R'", 'F', "R'", "F'", 'R', 'Uw'],
    explanation: 'The universal edge pairing engine on 4x4: slices open the top 2 layers to connect matching edge halves, flips the paired edge, and slices back to reconstruct all completed centers.',
    tactileTip: 'Uw turns the top 2 layers together smoothly.',
    mnemonic: 'Slice open, flip edge, slice back.',
    moveSteps: [
      { move: "Uw'", title: 'Up Wide Prime', instruction: 'Turn top two layers 90° counter-clockwise.', fingerTrick: 'Left index wide pull.', affectedLayer: 'Uw', spokenText: 'Up wide prime.' },
      { move: 'R', title: 'Right Up', instruction: 'Lift right column.', fingerTrick: 'Wrist.', affectedLayer: 'R', spokenText: 'Right.' },
      { move: 'U', title: 'Top Clockwise', instruction: 'Flick top.', fingerTrick: 'Index.', affectedLayer: 'U', spokenText: 'Up.' },
      { move: "R'", title: 'Right Down', instruction: 'Retract right column.', fingerTrick: 'Wrist.', affectedLayer: 'R', spokenText: 'Right prime.' },
      { move: 'F', title: 'Front Clockwise', instruction: 'Turn front face 90°.', fingerTrick: 'Index push.', affectedLayer: 'F', spokenText: 'Front.' },
      { move: "R'", title: 'Right Down', instruction: 'Retract right column.', fingerTrick: 'Wrist.', affectedLayer: 'R', spokenText: 'Right prime.' },
      { move: "F'", title: 'Front Prime', instruction: 'Restore front face.', fingerTrick: 'Thumb pull.', affectedLayer: 'F', spokenText: 'Front prime.' },
      { move: 'R', title: 'Right Up', instruction: 'Lock completed dedge.', fingerTrick: 'Wrist.', affectedLayer: 'R', spokenText: 'Right.' },
      { move: 'Uw', title: 'Up Wide Clockwise', instruction: 'Slice top two layers 90° clockwise back to restore all centers.', fingerTrick: 'Right index double pull.', affectedLayer: 'Uw', spokenText: 'Up wide.' },
    ],
  },
  {
    id: '4x4-oll-parity',
    cubeType: '4x4',
    category: '4x4 Parity Stage',
    stageName: 'Stage 3: Special Parity',
    name: '4x4 OLL Parity (Single Dedge Flip)',
    shortName: 'Rw U2 x Rw U2 Rw U2 Rw\' U2 Lw U2 Rw\' U2 Rw U2 Rw\' U2 Rw\'',
    difficulty: 'Advanced',
    moves: ['Rw', 'U2', 'x', 'Rw', 'U2', 'Rw', 'U2', "Rw'", 'U2', 'Lw', 'U2', "Rw'", 'U2', 'Rw', 'U2', "Rw'", 'U2', "Rw'"],
    explanation: 'The most iconic big-cube algorithm! On a 4x4, an odd permutation can leave a single edge pair flipped on the top layer—a state strictly impossible on a 3x3. This algorithm flips the edge without altering any other piece.',
    tactileTip: 'Notice the rhythmic pattern: Every alternating move is a U2 double flick. Tilt the whole cube forward at move 3 (x).',
    mnemonic: 'Rw U2, tilt cube, Rw U2, Rw U2, Rw\' U2, Lw U2, Rw\' U2, Rw U2, Rw\' U2, Rw\'.',
    moveSteps: [
      { move: 'Rw', title: 'Right Wide Up', instruction: 'Turn outer 2 right layers upwards 90°.', fingerTrick: 'Right wrist roll up.', affectedLayer: 'Rw', spokenText: 'Right wide.' },
      { move: 'U2', title: 'Top Double', instruction: 'Turn top layer 180°.', fingerTrick: 'Double flick.', affectedLayer: 'U', spokenText: 'Up two.' },
      { move: 'x', title: 'Cube Tilt Forward', instruction: 'Rotate the entire cube 90° towards you around the X axis.', fingerTrick: 'Tilt entire puzzle.', affectedLayer: 'All', spokenText: 'Rotate cube forward.' },
      { move: 'Rw', title: 'Right Wide Up', instruction: 'Turn 2 right layers upwards 90°.', fingerTrick: 'Right wrist.', affectedLayer: 'Rw', spokenText: 'Right wide.' },
      { move: 'U2', title: 'Top Double', instruction: '180° rotation on the top layer.', fingerTrick: 'Double flick.', affectedLayer: 'U', spokenText: 'Up two.' },
      { move: 'Rw', title: 'Right Wide Up', instruction: 'Turn 2 right layers upwards 90°.', fingerTrick: 'Right wrist.', affectedLayer: 'Rw', spokenText: 'Right wide.' },
      { move: 'U2', title: 'Top Double', instruction: '180° rotation.', fingerTrick: 'Double flick.', affectedLayer: 'U', spokenText: 'Up two.' },
      { move: "Rw'", title: 'Right Wide Down', instruction: 'Pull 2 right layers downwards 90°.', fingerTrick: 'Right wrist pull.', affectedLayer: 'Rw', spokenText: 'Right wide prime.' },
      { move: 'U2', title: 'Top Double', instruction: '180° rotation.', fingerTrick: 'Double flick.', affectedLayer: 'U', spokenText: 'Up two.' },
      { move: 'Lw', title: 'Left Wide Down', instruction: 'Turn 2 left layers downwards 90° away from top.', fingerTrick: 'Left wrist roll.', affectedLayer: 'Lw', spokenText: 'Left wide.' },
      { move: 'U2', title: 'Top Double', instruction: '180° rotation.', fingerTrick: 'Double flick.', affectedLayer: 'U', spokenText: 'Up two.' },
      { move: "Rw'", title: 'Right Wide Down', instruction: 'Pull 2 right layers downwards 90°.', fingerTrick: 'Right wrist.', affectedLayer: 'Rw', spokenText: 'Right wide prime.' },
      { move: 'U2', title: 'Top Double', instruction: '180° rotation.', fingerTrick: 'Double flick.', affectedLayer: 'U', spokenText: 'Up two.' },
      { move: 'Rw', title: 'Right Wide Up', instruction: 'Turn 2 right layers upwards 90°.', fingerTrick: 'Right wrist.', affectedLayer: 'Rw', spokenText: 'Right wide.' },
      { move: 'U2', title: 'Top Double', instruction: '180° rotation.', fingerTrick: 'Double flick.', affectedLayer: 'U', spokenText: 'Up two.' },
      { move: "Rw'", title: 'Right Wide Down', instruction: 'Pull 2 right layers downwards 90°.', fingerTrick: 'Right wrist.', affectedLayer: 'Rw', spokenText: 'Right wide prime.' },
      { move: 'U2', title: 'Top Double', instruction: '180° rotation.', fingerTrick: 'Double flick.', affectedLayer: 'U', spokenText: 'Up two.' },
      { move: "Rw'", title: 'Right Wide Down', instruction: 'Final 2 right layers downwards to complete the parity resolution.', fingerTrick: 'Right wrist snap.', affectedLayer: 'Rw', spokenText: 'Right wide prime.' },
    ],
  },
  {
    id: '4x4-pll-parity',
    cubeType: '4x4',
    category: '4x4 Parity Stage',
    stageName: 'Stage 3: Special Parity',
    name: '4x4 PLL Parity (Opposite Dedges Swap)',
    shortName: '2R2 U2 2R2 Uw2 2R2 Uw2',
    difficulty: 'Advanced',
    moves: ['2R2', 'U2', '2R2', 'Uw2', '2R2', 'Uw2'],
    explanation: 'Swaps two opposite edge blocks during PLL. An even-order parity that does not exist on 3x3 or 5x5! Extremely fast to execute with finger slices.',
    tactileTip: '2R2 turns the inner right slice 180°. Uw2 turns the top 2 layers 180° together.',
    mnemonic: 'Inner right 2, top 2, inner right 2, wide top 2, inner right 2, wide top 2.',
    moveSteps: [
      { move: '2R2', title: 'Inner Right Double', instruction: 'Spin 2nd layer from right 180°.', fingerTrick: 'Double slice flick.', affectedLayer: '2R', spokenText: 'Inner right slice two.' },
      { move: 'U2', title: 'Top Double', instruction: 'Spin top face 180°.', fingerTrick: 'Double flick.', affectedLayer: 'U', spokenText: 'Up two.' },
      { move: '2R2', title: 'Inner Right Double', instruction: 'Spin 2nd layer from right 180°.', fingerTrick: 'Double slice flick.', affectedLayer: '2R', spokenText: 'Inner right slice two.' },
      { move: 'Uw2', title: 'Up Wide Double', instruction: 'Spin top two layers together 180°.', fingerTrick: 'Wide double pull.', affectedLayer: 'Uw', spokenText: 'Up wide two.' },
      { move: '2R2', title: 'Inner Right Double', instruction: 'Spin 2nd layer from right 180°.', fingerTrick: 'Double slice flick.', affectedLayer: '2R', spokenText: 'Inner right slice two.' },
      { move: 'Uw2', title: 'Up Wide Double', instruction: 'Spin top two layers together 180° to resolve parity.', fingerTrick: 'Wide double pull.', affectedLayer: 'Uw', spokenText: 'Up wide two.' },
    ],
  },

  // ==========================================
  // 5x5: PROFESSOR'S CUBE (REDUCTION METHOD)
  // ==========================================
  {
    id: '5x5-center-strip-insert',
    cubeType: '5x5',
    category: '5x5 Centers Stage',
    stageName: 'Reduction Stage 1: Centers',
    name: '1x3 Center Strip Insert & Preserve',
    shortName: 'Rw U Rw\'',
    difficulty: 'Beginner',
    moves: ['Rw', 'U', "Rw'"],
    explanation: 'In 5x5 speedcubing, centers consist of a 3x3 block (9 pieces total on each face). This algorithm slides a built 1x3 strip into an opposing face, moves it out of the firing line, and restores previously placed centers.',
    tactileTip: 'Rw means turn BOTH the outer right layer and inner right slice simultaneously (2 layers wide).',
    mnemonic: 'Wide right up, turn top, wide right down.',
    moveSteps: [
      {
        move: 'Rw',
        title: 'Right Wide (2 Layers)',
        instruction: 'Turn both the outer right layer and inner right slice 90° clockwise upwards.',
        fingerTrick: 'Grip both right layers with right hand and roll wrist upwards.',
        affectedLayer: 'Rw',
        spokenText: 'Right wide.',
      },
      {
        move: 'U',
        title: 'Up Face',
        instruction: 'Turn top layer 90° clockwise to rotate the inserted strip out of the slice lane.',
        fingerTrick: 'Right index finger flick.',
        affectedLayer: 'U',
        spokenText: 'Up.',
      },
      {
        move: "Rw'",
        title: 'Right Wide Prime',
        instruction: 'Bring both right layers back down 90° to restore your bottom centers.',
        fingerTrick: 'Roll right wrist downwards.',
        affectedLayer: 'Rw',
        spokenText: 'Right wide prime.',
      },
    ],
  },
  {
    id: '5x5-center-commutator',
    cubeType: '5x5',
    category: '5x5 Centers Stage',
    stageName: 'Reduction Stage 1: Last 2 Centers',
    name: 'Inner Slice Commutator (Center Dot Swap)',
    shortName: '2R U 2R\' U 2R U2 2R\'',
    difficulty: 'Intermediate',
    moves: ['2R', 'U', "2R'", 'U', '2R', 'U2', "2R'"],
    explanation: 'Swaps one single misaligned center piece between the top and front centers without scrambling any other completed 5x5 centers. Equivalent to Sune executed strictly on the inner slice.',
    tactileTip: '2R indicates the 2nd layer from the right (the inner slice only, keeping the outer right layer fixed).',
    mnemonic: 'Inner right up, top, inner down, top, inner up, top two, inner down.',
    moveSteps: [
      { move: '2R', title: 'Inner Right Slice Up', instruction: 'Push only the 2nd layer from right upwards.', fingerTrick: 'Right thumb/middle slice push.', affectedLayer: '2R', spokenText: 'Inner right slice.' },
      { move: 'U', title: 'Top Clockwise', instruction: 'Rotate top face 90°.', fingerTrick: 'Right index flick.', affectedLayer: 'U', spokenText: 'Up.' },
      { move: "2R'", title: 'Inner Right Slice Down', instruction: 'Pull the 2nd layer back down.', fingerTrick: 'Right ring finger pull.', affectedLayer: '2R', spokenText: 'Inner right slice prime.' },
      { move: 'U', title: 'Top Clockwise', instruction: 'Rotate top face 90°.', fingerTrick: 'Right index flick.', affectedLayer: 'U', spokenText: 'Up.' },
      { move: '2R', title: 'Inner Right Slice Up', instruction: 'Lift 2nd layer upwards.', fingerTrick: 'Slice push.', affectedLayer: '2R', spokenText: 'Inner right slice.' },
      { move: 'U2', title: 'Top 180° Turn', instruction: 'Spin top face 180°.', fingerTrick: 'Double index-middle flick.', affectedLayer: 'U', spokenText: 'Up two.' },
      { move: "2R'", title: 'Inner Right Slice Down', instruction: 'Restore inner slice to lock swapped piece.', fingerTrick: 'Slice pull down.', affectedLayer: '2R', spokenText: 'Inner right slice prime.' },
    ],
  },
  {
    id: '5x5-edge-flipping',
    cubeType: '5x5',
    category: '5x5 Edge Pairing',
    stageName: 'Reduction Stage 2: Wing Alignment',
    name: 'Edge Flip Algorithm (Freeslicing Core)',
    shortName: 'R U R\' F R\' F\' R',
    difficulty: 'Intermediate',
    moves: ['R', 'U', "R'", 'F', "R'", "F'", 'R'],
    explanation: 'Flips the front-right composite edge upside down in place. When combined with wide slice moves (like Uw\' or Dw\'), this algorithm pairs wing pieces to create complete 1x3 edge groups.',
    tactileTip: 'Extremely fluid finger sequence: R U R\' immediately into a sledgehammer variant F R\' F\' R.',
    mnemonic: 'Lift, flick, drop, face roll, drop, face close, lift.',
    moveSteps: [
      { move: 'R', title: 'Right Up', instruction: 'Lift right layer.', fingerTrick: 'Wrist.', affectedLayer: 'R', spokenText: 'Right.' },
      { move: 'U', title: 'Up Clockwise', instruction: 'Flick top.', fingerTrick: 'Index.', affectedLayer: 'U', spokenText: 'Up.' },
      { move: "R'", title: 'Right Down', instruction: 'Drop right layer.', fingerTrick: 'Wrist.', affectedLayer: 'R', spokenText: 'Right prime.' },
      { move: 'F', title: 'Front Clockwise', instruction: 'Roll front face.', fingerTrick: 'Right index down.', affectedLayer: 'F', spokenText: 'Front.' },
      { move: "R'", title: 'Right Down', instruction: 'Drop right layer.', fingerTrick: 'Right wrist down.', affectedLayer: 'R', spokenText: 'Right prime.' },
      { move: "F'", title: 'Front Counter', instruction: 'Close front face.', fingerTrick: 'Right thumb up.', affectedLayer: 'F', spokenText: 'Front prime.' },
      { move: 'R', title: 'Right Up', instruction: 'Lift right layer to lock the flipped edge.', fingerTrick: 'Right wrist up.', affectedLayer: 'R', spokenText: 'Right.' },
    ],
  },
  {
    id: '5x5-freeslice-pairing',
    cubeType: '5x5',
    category: '5x5 Edge Pairing',
    stageName: 'Reduction Stage 2: Freeslice Pairing',
    name: 'Wide Slice-Flip-Slice (1x3 Edge Trio Assembly)',
    shortName: 'Uw\' (R U R\' F R\' F\' R) Uw',
    difficulty: 'Intermediate',
    moves: ['Uw\'', 'R', 'U', "R'", 'F', "R'", "F'", 'R', 'Uw'],
    explanation: 'The standard modern freeslice mechanism on 5x5: slices open the middle layer to connect a wing to the central edge, flips the paired edge, and slices back to restore all centers.',
    tactileTip: 'Uw means turning the top 2 layers together as a single block.',
    mnemonic: 'Slice open, flip edge, slice back.',
    moveSteps: [
      { move: "Uw'", title: 'Up Wide Prime (2 Layers)', instruction: 'Turn top two layers 90° counter-clockwise to join wings.', fingerTrick: 'Left index on upper 2 slices.', affectedLayer: 'Uw', spokenText: 'Up wide prime.' },
      { move: 'R', title: 'Right Up', instruction: 'Lift right column.', fingerTrick: 'Wrist.', affectedLayer: 'R', spokenText: 'Right.' },
      { move: 'U', title: 'Top Clockwise', instruction: 'Flick top layer.', fingerTrick: 'Right index.', affectedLayer: 'U', spokenText: 'Up.' },
      { move: "R'", title: 'Right Down', instruction: 'Retract right column.', fingerTrick: 'Wrist.', affectedLayer: 'R', spokenText: 'Right prime.' },
      { move: 'F', title: 'Front Clockwise', instruction: 'Turn front face 90°.', fingerTrick: 'Index push.', affectedLayer: 'F', spokenText: 'Front.' },
      { move: "R'", title: 'Right Down', instruction: 'Retract right column.', fingerTrick: 'Wrist.', affectedLayer: 'R', spokenText: 'Right prime.' },
      { move: "F'", title: 'Front Counter', instruction: 'Restore front face.', fingerTrick: 'Thumb pull.', affectedLayer: 'F', spokenText: 'Front prime.' },
      { move: 'R', title: 'Right Up', instruction: 'Lift right column.', fingerTrick: 'Wrist.', affectedLayer: 'R', spokenText: 'Right.' },
      { move: 'Uw', title: 'Up Wide Clockwise', instruction: 'Slice top two layers 90° clockwise back to restore all centers.', fingerTrick: 'Right index double pull.', affectedLayer: 'Uw', spokenText: 'Up wide.' },
    ],
  },
  {
    id: '5x5-oll-parity',
    cubeType: '5x5',
    category: '5x5 Parity Stage',
    stageName: 'Reduction Stage 3: Special Parity',
    name: '5x5 OLL Parity (Single Wing Flip)',
    shortName: 'Rw U2 x Rw U2 Rw U2 Rw\' U2 Lw U2 Rw\' U2 Rw U2 Rw\' U2 Rw\'',
    difficulty: 'Advanced',
    moves: ['Rw', 'U2', 'x', 'Rw', 'U2', 'Rw', 'U2', "Rw'", 'U2', 'Lw', 'U2', "Rw'", 'U2', 'Rw', 'U2', "Rw'", 'U2', "Rw'"],
    explanation: 'The big-cube parity! In 5x5, a single edge wing pair can end up flipped upside down—a state impossible on a regular 3x3. This algorithm flips the wing while preserving every other piece.',
    tactileTip: 'Observe the rhythm: Every second move is U2. There is an early full cube rotation (x = tilt whole cube forward). Practice in 3 chunks of U2 beats.',
    mnemonic: 'Rw U2, tilt cube, Rw U2, Rw U2, Rw\' U2, Lw U2, Rw\' U2, Rw U2, Rw\' U2, Rw\'.',
    moveSteps: [
      { move: 'Rw', title: 'Right Wide Up', instruction: 'Turn outer 2 right layers upwards 90°.', fingerTrick: 'Right wrist roll up.', affectedLayer: 'Rw', spokenText: 'Right wide.' },
      { move: 'U2', title: 'Top Double', instruction: 'Turn top layer 180°.', fingerTrick: 'Double flick.', affectedLayer: 'U', spokenText: 'Up two.' },
      { move: 'x', title: 'Cube Tilt Forward', instruction: 'Rotate the entire cube 90° towards you around the X axis.', fingerTrick: 'Tilt entire puzzle.', affectedLayer: 'All', spokenText: 'Rotate cube forward.' },
      { move: 'Rw', title: 'Right Wide Up', instruction: 'Turn 2 right layers upwards 90°.', fingerTrick: 'Right wrist.', affectedLayer: 'Rw', spokenText: 'Right wide.' },
      { move: 'U2', title: 'Top Double', instruction: '180° rotation on the top layer.', fingerTrick: 'Double flick.', affectedLayer: 'U', spokenText: 'Up two.' },
      { move: 'Rw', title: 'Right Wide Up', instruction: 'Turn 2 right layers upwards 90°.', fingerTrick: 'Right wrist.', affectedLayer: 'Rw', spokenText: 'Right wide.' },
      { move: 'U2', title: 'Top Double', instruction: '180° rotation.', fingerTrick: 'Double flick.', affectedLayer: 'U', spokenText: 'Up two.' },
      { move: "Rw'", title: 'Right Wide Down', instruction: 'Pull 2 right layers downwards 90°.', fingerTrick: 'Right wrist pull.', affectedLayer: 'Rw', spokenText: 'Right wide prime.' },
      { move: 'U2', title: 'Top Double', instruction: '180° rotation.', fingerTrick: 'Double flick.', affectedLayer: 'U', spokenText: 'Up two.' },
      { move: 'Lw', title: 'Left Wide Down', instruction: 'Turn 2 left layers downwards 90° away from top.', fingerTrick: 'Left wrist roll.', affectedLayer: 'Lw', spokenText: 'Left wide.' },
      { move: 'U2', title: 'Top Double', instruction: '180° rotation.', fingerTrick: 'Double flick.', affectedLayer: 'U', spokenText: 'Up two.' },
      { move: "Rw'", title: 'Right Wide Down', instruction: 'Pull 2 right layers downwards 90°.', fingerTrick: 'Right wrist.', affectedLayer: 'Rw', spokenText: 'Right wide prime.' },
      { move: 'U2', title: 'Top Double', instruction: '180° rotation.', fingerTrick: 'Double flick.', affectedLayer: 'U', spokenText: 'Up two.' },
      { move: 'Rw', title: 'Right Wide Up', instruction: 'Turn 2 right layers upwards 90°.', fingerTrick: 'Right wrist.', affectedLayer: 'Rw', spokenText: 'Right wide.' },
      { move: 'U2', title: 'Top Double', instruction: '180° rotation.', fingerTrick: 'Double flick.', affectedLayer: 'U', spokenText: 'Up two.' },
      { move: "Rw'", title: 'Right Wide Down', instruction: 'Pull 2 right layers downwards 90°.', fingerTrick: 'Right wrist.', affectedLayer: 'Rw', spokenText: 'Right wide prime.' },
      { move: 'U2', title: 'Top Double', instruction: '180° rotation.', fingerTrick: 'Double flick.', affectedLayer: 'U', spokenText: 'Up two.' },
      { move: "Rw'", title: 'Right Wide Down', instruction: 'Final 2 right layers downwards to complete the parity resolution.', fingerTrick: 'Right wrist snap.', affectedLayer: 'Rw', spokenText: 'Right wide prime.' },
    ],
  },
  {
    id: '5x5-pll-parity',
    cubeType: '5x5',
    category: '5x5 Parity Stage',
    stageName: 'Reduction Stage 3: Special Parity',
    name: '5x5 PLL Parity (Opposite Wings Swap)',
    shortName: '2R2 U2 2R2 Uw2 2R2 2Uw2',
    difficulty: 'Advanced',
    moves: ['2R2', 'U2', '2R2', 'Uw2', '2R2', '2Uw2'],
    explanation: 'Swaps the outer wings of two opposite edges during the Last 2 Edges (L2E) or final PLL stage. Ultra compact and fast when executed with slice flicks.',
    tactileTip: '2R2 is a double turn on the inner right slice. Uw2 is a double turn of the upper 2 layers. 2Uw2 is a double turn of the 2nd upper layer only.',
    mnemonic: 'Inner right 2, top 2, inner right 2, wide top 2, inner right 2, 2nd slice 2.',
    moveSteps: [
      { move: '2R2', title: 'Inner Right Double', instruction: 'Spin 2nd layer from right 180°.', fingerTrick: 'Double slice flick.', affectedLayer: '2R', spokenText: 'Inner right slice two.' },
      { move: 'U2', title: 'Top Double', instruction: 'Spin top face 180°.', fingerTrick: 'Double flick.', affectedLayer: 'U', spokenText: 'Up two.' },
      { move: '2R2', title: 'Inner Right Double', instruction: 'Spin 2nd layer from right 180°.', fingerTrick: 'Double slice flick.', affectedLayer: '2R', spokenText: 'Inner right slice two.' },
      { move: 'Uw2', title: 'Up Wide Double', instruction: 'Spin top two layers together 180°.', fingerTrick: 'Wide double pull.', affectedLayer: 'Uw', spokenText: 'Up wide two.' },
      { move: '2R2', title: 'Inner Right Double', instruction: 'Spin 2nd layer from right 180°.', fingerTrick: 'Double slice flick.', affectedLayer: '2R', spokenText: 'Inner right slice two.' },
      { move: '2Uw2', title: 'Inner Up Slice Double', instruction: 'Spin only the 2nd slice from top 180° to resolve the wing cycle.', fingerTrick: 'Middle index flick.', affectedLayer: '2Uw', spokenText: 'Inner up slice two.' },
    ],
  },
];

export function getAlgorithmsByCube(type: CubeType): Algorithm[] {
  return CUBE_ALGORITHMS.filter((a) => a.cubeType === type);
}

export interface NotationInfo {
  notation: string;
  name: string;
  face: string;
  angle: string;
  description: string;
  fingerTrick: string;
}

export const NOTATION_GUIDE_3X3: NotationInfo[] = [
  { notation: 'R', name: 'Right Clockwise', face: 'Right Face', angle: '90° Clockwise', description: 'Turn right side upwards away from you.', fingerTrick: 'Right wrist roll up.' },
  { notation: "R'", name: 'Right Prime', face: 'Right Face', angle: '90° Counter-Clockwise', description: 'Turn right side downwards towards you.', fingerTrick: 'Right wrist roll down.' },
  { notation: 'R2', name: 'Right Double', face: 'Right Face', angle: '180° Turn', description: 'Spin right side half a full circle.', fingerTrick: 'Double wrist flick.' },
  { notation: 'U', name: 'Up Clockwise', face: 'Top Face', angle: '90° Clockwise', description: 'Turn top layer leftwards.', fingerTrick: 'Right index finger flick.' },
  { notation: "U'", name: 'Up Prime', face: 'Top Face', angle: '90° Counter-Clockwise', description: 'Turn top layer rightwards.', fingerTrick: 'Left index finger flick.' },
  { notation: 'U2', name: 'Up Double', face: 'Top Face', angle: '180° Turn', description: 'Spin top layer 180°.', fingerTrick: 'Index then middle finger double flick.' },
  { notation: 'F', name: 'Front Clockwise', face: 'Front Face', angle: '90° Clockwise', description: 'Rotate front face like a steering wheel to the right.', fingerTrick: 'Right index pushes downward.' },
  { notation: "F'", name: 'Front Prime', face: 'Front Face', angle: '90° Counter-Clockwise', description: 'Rotate front face like a steering wheel to the left.', fingerTrick: 'Right thumb lifts upward.' },
  { notation: 'L', name: 'Left Clockwise', face: 'Left Face', angle: '90° Clockwise', description: 'Turn left side downwards towards you.', fingerTrick: 'Left wrist roll down.' },
  { notation: "L'", name: 'Left Prime', face: 'Left Face', angle: '90° Counter-Clockwise', description: 'Turn left side upwards away from you.', fingerTrick: 'Left wrist roll up.' },
  { notation: 'D', name: 'Down Clockwise', face: 'Bottom Face', angle: '90° Clockwise', description: 'Turn bottom layer rightwards.', fingerTrick: 'Left ring finger flick.' },
  { notation: "D'", name: 'Down Prime', face: 'Bottom Face', angle: '90° Counter-Clockwise', description: 'Turn bottom layer leftwards.', fingerTrick: 'Right ring finger flick.' },
  { notation: 'M', name: 'Middle Slice', face: 'Vertical Center', angle: '90° Downward', description: 'Turn center slice between L and R downwards (same dir as L).', fingerTrick: 'Ring finger pull on back-bottom.' },
];

export const NOTATION_GUIDE_4X4: NotationInfo[] = [
  { notation: 'Rw', name: 'Right Wide (2 Layers)', face: 'Right Outer & Inner', angle: '90° Clockwise', description: 'Turn outer right layer AND inner right slice together.', fingerTrick: 'Grip both right layers with right palm.' },
  { notation: "Rw'", name: 'Right Wide Prime', face: 'Right 2 Layers', angle: '90° Counter-Clockwise', description: 'Pull outer 2 right layers downwards together.', fingerTrick: 'Pull both right layers down with wrist.' },
  { notation: '2R', name: 'Inner Right Slice', face: '2nd Slice from Right', angle: '90° Clockwise', description: 'Turn ONLY the 2nd layer from the right; outer right layer stays still.', fingerTrick: 'Right middle finger isolates slice.' },
  { notation: '2R2', name: 'Inner Right Double', face: '2nd Slice from Right', angle: '180° Turn', description: 'Spin only the inner right slice 180° (key parity move).', fingerTrick: 'Double slice flick.' },
  { notation: 'Uw', name: 'Up Wide (2 Layers)', face: 'Top Outer & Inner', angle: '90° Clockwise', description: 'Turn top 2 layers together to freeslice and connect edge pieces.', fingerTrick: 'Index and middle grip top two layers.' },
  { notation: "Uw'", name: 'Up Wide Prime', face: 'Top 2 Layers', angle: '90° Counter-Clockwise', description: 'Turn top 2 layers counter-clockwise.', fingerTrick: 'Left index and middle pull.' },
  { notation: 'Uw2', name: 'Up Wide Double', face: 'Top 2 Layers', angle: '180° Turn', description: 'Spin top 2 layers together 180°.', fingerTrick: 'Double wide flick.' },
  { notation: 'Lw', name: 'Left Wide (2 Layers)', face: 'Left Outer & Inner', angle: '90° Clockwise', description: 'Turn outer left layer AND inner left slice together downwards.', fingerTrick: 'Left palm roll.' },
];

export const NOTATION_GUIDE_5X5: NotationInfo[] = [
  { notation: 'Rw / r', name: 'Right Wide', face: 'Right 2 Layers', angle: '90° Clockwise', description: 'Turn outer right layer AND inner right slice together.', fingerTrick: 'Grip both right layers with palm.' },
  { notation: "Rw'", name: 'Right Wide Prime', face: 'Right 2 Layers', angle: '90° Counter-Clockwise', description: 'Pull outer 2 right layers downwards together.', fingerTrick: 'Pull both right layers down.' },
  { notation: '2R', name: 'Inner Right Slice', face: '2nd Layer from Right', angle: '90° Clockwise', description: 'Turn ONLY the inner right slice; leave outer right untouched.', fingerTrick: 'Right thumb isolates slice.' },
  { notation: 'Uw', name: 'Up Wide', face: 'Top 2 Layers', angle: '90° Clockwise', description: 'Turn top 2 layers together to freeslice and connect wings.', fingerTrick: 'Index and middle grip top two layers.' },
  { notation: '2U', name: 'Inner Up Slice', face: '2nd Layer from Top', angle: '90° Clockwise', description: 'Turn ONLY the 2nd layer slice from top.', fingerTrick: 'Index finger slice flick.' },
  { notation: 'Lw', name: 'Left Wide', face: 'Left 2 Layers', angle: '90° Clockwise', description: 'Turn outer left layer AND inner left slice together downwards.', fingerTrick: 'Left palm roll.' },
  { notation: '3Rw', name: '3-Layer Wide', face: 'Right 3 Layers', angle: '90° Clockwise', description: 'Turn right 3 layers together.', fingerTrick: 'Three-finger grip.' },
];
